name: Openwrt-fros-HC5962

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-plug-official.sh
  DIY_P2_SH: diy-config.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          clang \
          flex \
          g++ \
          gawk \
          gcc-multilib \
          gettext \
          git \
          libncurses5-dev \
          libssl-dev \
          make \
          python3 \
          python3-distutils \
          rsync \
          unzip \
          zlib1g-dev \
          file \
          wget \
          jq \
          time

    - name: Clone ImmortalWrt (Debug)
      run: |
        echo "Cloning from $REPO_URL branch $REPO_BRANCH"
        git clone -b $REPO_BRANCH --depth 1 "$REPO_URL" openwrt || { echo "Clone failed"; exit 1; }
        echo "Cloned directory contents:"
        ls -al openwrt

    - name: Prepare config files
      run: |
        echo "Copying config files..."
        cp "$GITHUB_WORKSPACE/$FEEDS_CONF" openwrt/feeds.conf.default
        cp "$GITHUB_WORKSPACE/$CONFIG_FILE" openwrt/.config
        chmod +x "$GITHUB_WORKSPACE/$DIY_P1_SH"
        chmod +x "$GITHUB_WORKSPACE/$DIY_P2_SH"

    - name: Run DIY scripts
      run: |
        cd openwrt
        echo "Running DIY scripts..."
        ../$DIY_P1_SH
        ../$DIY_P2_SH
        
    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build configuration
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        make -j$(nproc) V=s

    - name: Upload artifacts
      if: ${{ env.UPLOAD_FIRMWARE }}
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: |
          openwrt/bin/targets/*/*
          !openwrt/bin/targets/*/*.manifest
          !openwrt/bin/targets/*/*.buildinfo

    - name: Create release
      if: ${{ env.UPLOAD_RELEASE }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          openwrt/bin/targets/*/*/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
