# .github/workflows/your-workflow-name.yml
name: Workflow-1

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2
          
      - name: Install Dependencies
        working-directory: .
        run: go mod download

      - name: Check Go version and setup environment if needed
        run: |
          go version
          go env
        
      - name: Build Project
        run: go build -v ./...
