# .github/workflows/your-workflow-name.yml
name: Workflow-1

name: Go Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2
      - name: Install Dependencies
        run: |
		      go mod init
          go mod download
		      go env
        
      - name: Build Project
        run: go build -v ./...
